CREATE TABLE users(
  id VARCHAR (56) PRIMARY KEY UNIQUE NOT NULL,
  email VARCHAR (50) DEFAULT '',
  fname VARCHAR (140) DEFAULT '',
  lname VARCHAR (140) DEFAULT '',
  note VARCHAR (280) DEFAULT ''
);

CREATE TABLE people(
  id VARCHAR (56) PRIMARY KEY UNIQUE NOT NULL,
  stellar_secret VARCHAR UNIQUE NOT NULL,
  stellar_nonce VARCHAR UNIQUE NOT NULL,
  authy_id INTEGER DEFAULT NULL,
  authy_verified BOOLEAN DEFAULT false
);